## cartridge.properties for cartridge payone_commerce_sfra_changes
#Tue Jan 17 16:22:9 CEST 2026
demandware.cartridges.payone_commerce_sfra_changes.multipleLanguageStorefront=true
demandware.cartridges.payone_commerce_sfra_changes.id=payone_commerce_sfra_changes
demandware.cartridges.payone_commerce_sfra_changes.version=26.1.0
