## cartridge.properties for cartridge bm_payone_commerce
#Tue Jan 17 16:21:33 CEST 2026
demandware.cartridges.bm_payone_commerce.multipleLanguageStorefront=true
demandware.cartridges.bm_payone_commerce.id=bm_payone_commerce
demandware.cartridges.bm_payone_commerce.version=26.1.0
