email.hello=Hello {0},

order.placed.subject=Order {0} has been placed
order.placed.yourorder=Your order
order.placed.text=has been placed after PAYONE payment confirmation.
order.placed.thankyou=Thank you for shopping with us.

order.failed.subject=Order {0} payment failed
order.failed.text=We could not complete payment for order
order.failed.retry=Please contact customer support or retry payment
