## cartridge.properties for cartridge int_payone_commerce
#Tue Jan 17 16:21:2 CEST 2026
demandware.cartridges.int_payone_commerce.multipleLanguageStorefront=true
demandware.cartridges.int_payone_commerce.id=int_payone_commerce
demandware.cartridges.int_payone_commerce.version=26.1.0
