'use strict';

var Resource = require('dw/web/Resource');
var StringUtils = require('dw/util/StringUtils');
var server = require('server');
var PayoneCommonUtils = require('*/cartridge/scripts/payone/PayoneCommonUtils');
var payonePayPalHelper = require('*/cartridge/scripts/payone/payonePayPalHelper');

var PAYMENT_PRODUCT_IDS = {
    CARD_VISA: 1,
    CARD_AMEX: 2,
    CARD_MASTERCARD: 3,
    CARD_JCB: 125,
    CARD_DINERS: 132,
    APPLE_PAY: 302,
    GOOGLE_PAY: 320,
    PAYPAL: 840,
    WERO: 900,
    SEPA_DIRECT_DEBIT: 771,
    SECURED_INVOICE: 3390,
    SECURED_INSTALLMENT: 3391,
    SECURED_DIRECT_DEBIT: 3392,
    CASH_PAYMENT: 6000
};

var CARD_PAYMENT_PRODUCT_IDS = {
    visa: PAYMENT_PRODUCT_IDS.CARD_VISA,
    amex: PAYMENT_PRODUCT_IDS.CARD_AMEX,
    mastercard: PAYMENT_PRODUCT_IDS.CARD_MASTERCARD,
    jcb: PAYMENT_PRODUCT_IDS.CARD_JCB,
    diners: PAYMENT_PRODUCT_IDS.CARD_DINERS
};

var SUPPORTED_PAYMENT_METHODS = {
    PAYONE_COMMERCE_CARD: {
        formId: 'payoneCommerceCardForm',
        buildKey: 'card'
    },
    PAYONE_COMMERCE_SEPA: {
        formId: 'payoneCommerceSepaForm',
        buildKey: 'sepa'
    },
    PAYONE_COMMERCE_SECURE_INVOICE: {
        formId: 'payoneCommerceSecureInvoiceForm',
        buildKey: 'secureinvoice'
    },
    PAYONE_COMMERCE_SECURE_INSTALLMENT: {
        formId: 'payoneCommerceSecureInstallmentForm',
        buildKey: 'secureinstallment'
    },
    PAYONE_COMMERCE_SECURE_DIRECT_DEBIT: {
        formId: 'payoneCommerceSecureDirectDebitForm',
        buildKey: 'securedirectdebit'
    },
    PAYONE_COMMERCE_GOOGLEPAY: {
        formId: 'payoneCommerceGooglepayForm',
        buildKey: 'googlepay'
    },
    PAYONE_COMMERCE_PAYPAL: {
        formId: 'payoneCommercePaypalForm',
        buildKey: 'paypal'
    },
    PAYONE_COMMERCE_STORE_PAY: {
        formId: 'payoneCommerceStorePayForm',
        buildKey: 'storepay'
    },
    PAYONE_COMMERCE_WERO: {
        formId: 'payoneCommerceWeroForm',
        buildKey: 'wero'
    }
};

var DATE_OF_BIRTH_METHODS = {
    PAYONE_COMMERCE_SECURE_INVOICE: true,
    PAYONE_COMMERCE_SECURE_INSTALLMENT: true,
    PAYONE_COMMERCE_SECURE_DIRECT_DEBIT: true
};

var PHONE_NUMBER_METHODS = {
    PAYONE_COMMERCE_SECURE_INVOICE: 'secureInvoicePhoneNumber',
    PAYONE_COMMERCE_SECURE_INSTALLMENT: 'secureInstallmentPhoneNumber'
};

/**
 * Indicates whether the selected method requires checkout-only customer override data.
 *
 * @param {string} paymentMethodId - SFCC payment method id.
 * @returns {boolean} True when DOB/phone data must be collected from the form.
 */
function requiresCustomerOverride(paymentMethodId) {
    return !!(DATE_OF_BIRTH_METHODS[paymentMethodId] || PHONE_NUMBER_METHODS[paymentMethodId]);
}

/**
 * Returns the request parameter name generated by the SFCC form framework.
 *
 * @param {string} formId - SFCC form id.
 * @param {string} fieldId - SFCC field id.
 * @returns {string} Request parameter name.
 */
function getFormFieldName(formId, fieldId) {
    return 'dwfrm_' + formId + '_' + fieldId;
}

/**
 * Returns the payment-method configuration when implemented.
 *
 * @param {string} paymentMethodId - SFCC payment method id.
 * @returns {Object|null} Method configuration or null.
 */
function getPaymentMethodConfig(paymentMethodId) {
    return SUPPORTED_PAYMENT_METHODS[paymentMethodId] || null;
}

/**
 * Indicates whether the selected payment method has an implemented authorization input mapping.
 *
 * @param {string} paymentMethodId - SFCC payment method id.
 * @returns {boolean} True when implemented.
 */
function supportsPaymentMethod(paymentMethodId) {
    return !!getPaymentMethodConfig(paymentMethodId);
}

/**
 * Reads a posted field for the selected method from the request.
 *
 * @param {Object} req - SFRA request object.
 * @param {string} paymentMethodId - SFCC payment method id.
 * @param {string} fieldId - SFCC field id.
 * @returns {string|null} Posted field value or null.
 */
function getPostedField(req, paymentMethodId, fieldId) {
    var config = getPaymentMethodConfig(paymentMethodId);
    var fieldName;

    if (!config || !req || !req.form) {
        return null;
    }

    fieldName = getFormFieldName(config.formId, fieldId);

    return req.form[fieldName] || null;
}

/**
 * Reads a mandatory posted field for the selected method.
 *
 * @param {Object} req - SFRA request object.
 * @param {string} paymentMethodId - SFCC payment method id.
 * @param {string} fieldId - SFCC field id.
 * @returns {string|null} Posted field value or null.
 */
function getRequiredPostedField(req, paymentMethodId, fieldId) {
    return PayoneCommonUtils.trimString(getPostedField(req, paymentMethodId, fieldId), true);
}

/**
 * Reads a billing form field value safely.
 *
 * @param {Object} billingForm - SFRA billing form object.
 * @param {string[]} fieldPath - Nested form path.
 * @returns {string|null} Trimmed field value or null.
 */
function getBillingFormValue(billingForm, fieldPath) {
    var currentField = billingForm;
    var i;

    for (i = 0; currentField && fieldPath && i < fieldPath.length; i += 1) {
        currentField = currentField[fieldPath[i]];
    }

    return PayoneCommonUtils.trimString(
        currentField && Object.prototype.hasOwnProperty.call(currentField, 'value')
            ? currentField.value
            : null
    );
}

/**
 * Reads the posted token information for the selected method from the request.
 *
 * @param {Object} req - SFRA request object.
 * @param {string} paymentMethodId - SFCC payment method id.
 * @returns {string|null} Token information or null when unavailable.
 */
function getTokenInformation(req, paymentMethodId) {
    return getPostedField(req, paymentMethodId, 'tokenInformation');
}

/**
 * Reads the posted card type for the selected method from the request.
 *
 * @param {Object} req - SFRA request object.
 * @param {string} paymentMethodId - SFCC payment method id.
 * @returns {string|null} Card type or null when unavailable.
 */
function getCardType(req, paymentMethodId) {
    return getPostedField(req, paymentMethodId, 'cardType');
}

/**
 * Normalizes posted token information to the PAYONE paymentProcessingToken string.
 *
 * @param {string} tokenInformation - Raw posted token payload.
 * @returns {string|null} Payment processing token.
 */
function normalizeTokenInformation(tokenInformation) {
    var parsedTokenInformation;
    var normalizedToken;

    normalizedToken = PayoneCommonUtils.trimString(tokenInformation, true);

    if (!normalizedToken) {
        return null;
    }

    if (normalizedToken.charAt(0) === '{' || normalizedToken.charAt(0) === '[') {
        parsedTokenInformation = PayoneCommonUtils.parseJson(normalizedToken);
        normalizedToken = PayoneCommonUtils.trimString(
            parsedTokenInformation && (
                parsedTokenInformation.tokenValue
                || parsedTokenInformation.paymentProcessingToken
            ),
            true
        );
    }

    return normalizedToken;
}

/**
 * Parses a posted JSON payload into an object.
 *
 * @param {string} payload - Raw posted payload.
 * @returns {Object|null} Parsed object or null.
 */
function parsePostedJson(payload) {
    var normalizedPayload = PayoneCommonUtils.trimString(payload, true);

    if (!normalizedPayload) {
        return null;
    }

    return PayoneCommonUtils.parseJson(normalizedPayload);
}

/**
 * Maps a hosted-tokenization card type to a PAYONE payment product id.
 *
 * @param {string} cardType - Hosted tokenizer card type.
 * @returns {number|null} PAYONE payment product id.
 */
function getCardPaymentProductId(cardType) {
    var normalizedCardType = PayoneCommonUtils.trimString(cardType, true);

    if (!normalizedCardType) {
        return null;
    }

    return CARD_PAYMENT_PRODUCT_IDS[normalizedCardType.toLowerCase()] || null;
}

/**
 * Extracts the Google Pay encrypted payment data token from a posted payment data payload.
 *
 * @param {string} tokenInformation - Raw posted Google Pay payload.
 * @returns {string|null} Encrypted payment data token.
 */
function getGooglePayEncryptedPaymentData(tokenInformation) {
    var parsedTokenInformation = parsePostedJson(tokenInformation);
    var paymentToken;

    if (!parsedTokenInformation) {
        paymentToken = normalizeTokenInformation(tokenInformation);

        return paymentToken
            ? StringUtils.encodeBase64(paymentToken, 'UTF-8')
            : null;
    }

    paymentToken = PayoneCommonUtils.trimString(
        parsedTokenInformation.paymentMethodData
            && parsedTokenInformation.paymentMethodData.tokenizationData
            && parsedTokenInformation.paymentMethodData.tokenizationData.token,
        true
    );

    if (!paymentToken) {
        return null;
    }

    return StringUtils.encodeBase64(paymentToken, 'UTF-8');
}

/**
 * Extracts the approved PayPal checkout payload from the posted hidden field.
 *
 * @param {string} tokenInformation - Raw posted PayPal payload.
 * @returns {Object|null} Approved PayPal payload or null.
 */
function getPayPalApprovalData(tokenInformation) {
    var parsedTokenInformation = parsePostedJson(tokenInformation);

    if (!parsedTokenInformation || !parsedTokenInformation.approved) {
        return null;
    }

    return parsedTokenInformation;
}

/**
 * Extracts the selected Secure Installment context payload from the posted hidden field.
 *
 * @param {string} tokenInformation - Raw hidden-field payload.
 * @returns {Object|null} Selected Secure Installment data or null.
 */
function getSecureInstallmentSelectionData(tokenInformation) {
    var parsedTokenInformation = parsePostedJson(tokenInformation);

    if (!parsedTokenInformation || !parsedTokenInformation.contextKey || !parsedTokenInformation.installmentOptionId) {
        return null;
    }

    return parsedTokenInformation;
}

/**
 * Builds a PAYONE-compatible birth date from split form fields.
 *
 * @param {string|number} day - Day value.
 * @param {string|number} month - Month value.
 * @param {string|number} year - Year value.
 * @returns {string|null} Birth date in YYYYMMDD format.
 */
function buildBirthDateString(day, month, year) {
    var parsedDay = PayoneCommonUtils.toInt(day);
    var parsedMonth = PayoneCommonUtils.toInt(month);
    var parsedYear = PayoneCommonUtils.toInt(year);

    if (!parsedDay || !parsedMonth || !parsedYear) {
        return null;
    }

    if (parsedDay < 1 || parsedDay > 31 || parsedMonth < 1 || parsedMonth > 12 || parsedYear < 1900 || parsedYear > 2100) {
        return null;
    }

    return String(parsedYear)
        + ('0' + parsedMonth).slice(-2)
        + ('0' + parsedDay).slice(-2);
}

/**
 * Builds a bank-account information object when the required fields are present.
 *
 * @param {string} iban - IBAN value.
 * @param {string} accountHolder - Account holder value.
 * @returns {Object|null} PAYONE bankAccountInformation object.
 */
function buildBankAccountInformation(iban, accountHolder) {
    var normalizedIban = PayoneCommonUtils.trimString(iban, true);
    var normalizedAccountHolder = PayoneCommonUtils.trimString(accountHolder, true);

    if (!normalizedIban || !normalizedAccountHolder) {
        return null;
    }

    return {
        iban: normalizedIban,
        accountHolder: normalizedAccountHolder
    };
}

/**
 * Builds an account-holder name from posted billing address fields.
 *
 * @returns {string|null} Billing full name or null.
 */
function getBillingAccountHolder() {
    var billingForm = server.forms.getForm('billing');
    var firstName = getBillingFormValue(billingForm, ['addressFields', 'firstName']);
    var lastName = getBillingFormValue(billingForm, ['addressFields', 'lastName']);

    return [firstName, lastName].filter(function (value) {
        return !!value;
    }).join(' ') || null;
}

/**
 * Returns the payment-method specific birth-date field ids.
 *
 * @param {string} paymentMethodId - SFCC payment method id.
 * @returns {{day:string, month:string, year:string}} Birth-date field ids.
 */
function getBirthDateFieldIds(paymentMethodId) {
    if (paymentMethodId === 'PAYONE_COMMERCE_SECURE_INVOICE') {
        return {
            day: 'secureInvoiceBirthDay',
            month: 'secureInvoiceBirthMonth',
            year: 'secureInvoiceBirthYear'
        };
    }

    if (paymentMethodId === 'PAYONE_COMMERCE_SECURE_INSTALLMENT') {
        return {
            day: 'secureInstallmentBirthDay',
            month: 'secureInstallmentBirthMonth',
            year: 'secureInstallmentBirthYear'
        };
    }

    return {
        day: 'secureDebitBirthDay',
        month: 'secureDebitBirthMonth',
        year: 'secureDebitBirthYear'
    };
}

/**
 * Builds a lightweight customer-data override payload from checkout form fields.
 *
 * @param {string} paymentMethodId - SFCC payment method id.
 * @param {Object} req - SFRA request object.
 * @returns {Object|null} Customer/contact override payload or null.
 */
function buildCustomerOverride(paymentMethodId, req) {
    var customerOverride = {};
    var birthDate;
    var birthDateFieldIds;
    var phoneFieldId;
    var emailAddress;

    if (DATE_OF_BIRTH_METHODS[paymentMethodId]) {
        birthDateFieldIds = getBirthDateFieldIds(paymentMethodId);
        birthDate = buildBirthDateString(
            getPostedField(req, paymentMethodId, birthDateFieldIds.day),
            getPostedField(req, paymentMethodId, birthDateFieldIds.month),
            getPostedField(req, paymentMethodId, birthDateFieldIds.year)
        );

        if (!birthDate) {
            return null;
        }

        customerOverride.personalInformation = {
            dateOfBirth: birthDate
        };
    }

    phoneFieldId = PHONE_NUMBER_METHODS[paymentMethodId];
    if (phoneFieldId) {
        customerOverride.contactDetails = {
            phoneNumber: getRequiredPostedField(req, paymentMethodId, phoneFieldId)
        };

        if (!customerOverride.contactDetails.phoneNumber) {
            return null;
        }
    }

    if (paymentMethodId === 'PAYONE_COMMERCE_SECURE_INSTALLMENT') {
        emailAddress = getBillingFormValue(server.forms.getForm('billing'), ['contactInfoFields', 'email']);

        if (emailAddress) {
            customerOverride.contactDetails = customerOverride.contactDetails || {};
            customerOverride.contactDetails.emailAddress = emailAddress;
        }
    }

    return Object.keys(customerOverride).length ? customerOverride : null;
}

/**
 * Builds PAYONE secured-installment input.
 *
 * @param {Object} context - Builder context.
 * @returns {Object|null} PAYONE financing input payload.
 */
function buildSecureInstallmentPaymentMethodSpecificInput(context) {
    var safeContext = context || {};
    var selectionData = getSecureInstallmentSelectionData(safeContext.tokenInformation);
    var bankAccountInformation = buildBankAccountInformation(
        getPostedField(safeContext.req, safeContext.paymentMethodId, 'secureInstallmentIban'),
        getBillingAccountHolder(safeContext.req)
    );

    if (!selectionData || !bankAccountInformation) {
        return null;
    }

    return {
        financingPaymentMethodSpecificInput: {
            paymentProductId: PAYMENT_PRODUCT_IDS.SECURED_INSTALLMENT,
            paymentProduct3391SpecificInput: {
                installmentOptionId: selectionData.installmentOptionId,
                bankAccountInformation: bankAccountInformation
            }
        }
    };
}

/**
 * Builds PAYONE card payment input.
 *
 * @param {Object} context - Builder context.
 * @returns {Object|null} PAYONE card payment input payload.
 */
function buildCardPaymentMethodSpecificInput(context) {
    var safeContext = context || {};
    var paymentProcessingToken = normalizeTokenInformation(safeContext.tokenInformation);
    var paymentProductId = getCardPaymentProductId(getCardType(safeContext.req, safeContext.paymentMethodId));

    if (!paymentProcessingToken || !paymentProductId) {
        return null;
    }

    return {
        cardPaymentMethodSpecificInput: {
            paymentProcessingToken: paymentProcessingToken,
            paymentProductId: paymentProductId
        }
    };
}

/**
 * Builds PAYONE SEPA direct-debit input.
 *
 * @param {Object} context - Builder context.
 * @returns {Object|null} PAYONE SEPA direct-debit input payload.
 */
function buildSepaPaymentMethodSpecificInput(context) {
    var safeContext = context || {};
    var bankAccountInformation = buildBankAccountInformation(
        getPostedField(safeContext.req, safeContext.paymentMethodId, 'sepaIban'),
        getPostedField(safeContext.req, safeContext.paymentMethodId, 'sepaAccountHolder')
    );

    if (!bankAccountInformation) {
        return null;
    }

    return {
        sepaDirectDebitPaymentMethodSpecificInput: {
            paymentProductId: PAYMENT_PRODUCT_IDS.SEPA_DIRECT_DEBIT,
            paymentProduct771SpecificInput: {
                mandate: {
                    bankAccountIban: bankAccountInformation
                }
            }
        }
    };
}

/**
 * Builds PAYONE secured-invoice input.
 *
 * @returns {Object} PAYONE financing input payload.
 */
function buildSecureInvoicePaymentMethodSpecificInput() {
    return {
        financingPaymentMethodSpecificInput: {
            paymentProductId: PAYMENT_PRODUCT_IDS.SECURED_INVOICE
        }
    };
}

/**
 * Builds PAYONE secured-direct-debit input.
 *
 * @param {Object} context - Builder context.
 * @returns {Object|null} PAYONE financing input payload.
 */
function buildSecureDirectDebitPaymentMethodSpecificInput(context) {
    var safeContext = context || {};
    var bankAccountInformation = buildBankAccountInformation(
        getPostedField(safeContext.req, safeContext.paymentMethodId, 'secureDebitIban'),
        getPostedField(safeContext.req, safeContext.paymentMethodId, 'secureDebitAccountHolder')
    );

    if (!bankAccountInformation) {
        return null;
    }

    return {
        financingPaymentMethodSpecificInput: {
            paymentProductId: PAYMENT_PRODUCT_IDS.SECURED_DIRECT_DEBIT,
            paymentProduct3392SpecificInput: {
                bankAccountInformation: bankAccountInformation
            }
        }
    };
}

/**
 * Builds PAYONE Google Pay mobile payment input.
 *
 * @param {Object} context - Builder context.
 * @returns {Object|null} PAYONE mobile payment input payload.
 */
function buildGooglePayPaymentMethodSpecificInput(context) {
    var safeContext = context || {};
    var encryptedPaymentData = getGooglePayEncryptedPaymentData(safeContext.tokenInformation);

    if (!encryptedPaymentData) {
        return null;
    }

    return {
        mobilePaymentMethodSpecificInput: {
            paymentProductId: PAYMENT_PRODUCT_IDS.GOOGLE_PAY,
            encryptedPaymentData: encryptedPaymentData
        }
    };
}

/**
 * Builds PAYONE PayPal redirect input for the JavaScript SDK flow.
 *
 * @param {Object} context - Builder context.
 * @returns {Object|null} PAYONE redirect payment input payload.
 */
function buildPayPalPaymentMethodSpecificInput(context) {
    var safeContext = context || {};
    var approvalData = getPayPalApprovalData(safeContext.tokenInformation);

    if (!approvalData) {
        return null;
    }

    return payonePayPalHelper.buildPayPalPaymentMethodSpecificInput();
}

/**
 * Builds PAYONE Wero direct-sale redirect input.
 *
 * @returns {Object} PAYONE redirect payment input payload.
 */
function buildWeroPaymentMethodSpecificInput() {
    return {
        redirectPaymentMethodSpecificInput: {
            paymentProductId: PAYMENT_PRODUCT_IDS.WERO,
            requiresApproval: false
        }
    };
}

/**
 * Builds the PAYONE Store Pay input.
 * Store Pay creates only the checkout without executing a payment at checkout-creation time.
 *
 * @returns {Object} Empty payment input payload.
 */
function buildStorePayPaymentMethodSpecificInput() {
    return {};
}

/**
 * Resolves the builder function for a supported payment method.
 *
 * @param {string} buildKey - Configured builder key.
 * @returns {Function|null} Builder function or null.
 */
function getPaymentMethodBuilder(buildKey) {
    switch (buildKey) {
        case 'card':
            return buildCardPaymentMethodSpecificInput;
        case 'sepa':
            return buildSepaPaymentMethodSpecificInput;
        case 'secureinvoice':
            return buildSecureInvoicePaymentMethodSpecificInput;
        case 'secureinstallment':
            return buildSecureInstallmentPaymentMethodSpecificInput;
        case 'securedirectdebit':
            return buildSecureDirectDebitPaymentMethodSpecificInput;
        case 'googlepay':
            return buildGooglePayPaymentMethodSpecificInput;
        case 'paypal':
            return buildPayPalPaymentMethodSpecificInput;
        case 'wero':
            return buildWeroPaymentMethodSpecificInput;
        case 'storepay':
            return buildStorePayPaymentMethodSpecificInput;
        default:
            return null;
    }
}

/**
 * Builds PAYONE payment-method specific input from posted checkout data.
 *
 * @param {string} paymentMethodId - SFCC payment method id.
 * @param {string} tokenInformation - Tokenized payment information.
 * @param {Object} [req] - SFRA request object.
 * @returns {Object|null} PAYONE paymentMethodSpecificInput payload.
 */
function buildPaymentMethodSpecificInput(paymentMethodId, tokenInformation, req) {
    var config = getPaymentMethodConfig(paymentMethodId);
    var builder;

    if (!config) {
        return null;
    }

    builder = getPaymentMethodBuilder(config.buildKey);

    if (!builder) {
        return null;
    }

    return builder({
        req: req,
        paymentMethodId: paymentMethodId,
        tokenInformation: tokenInformation
    });
}

/**
 * Returns a generic message for methods whose storefront handling is not implemented yet.
 *
 * @returns {string} Localized message.
 */
function getUnsupportedMethodMessage() {
    return Resource.msg('error.not.implemented', 'common', null);
}

/**
* Builds the Apple Pay specific input object required for Payone payment authorization.
*
* @param {dw.order.Order} order - The order object containing payment instruments and order details.
* @param {Object} context - The context object containing Apple Pay payment data and method information.
* @returns {Object} An object containing the mobilePaymentMethodSpecificInput structure for Apple Pay authorization.
*/
function buildApplePaySpecificInput(order, context) {
    var Site = require('dw/system/Site').getCurrent();
    var payoneCommerceApplePayHelper = require('*/cartridge/scripts/helpers/payoneCommerceApplePayHelper.js');
    var payoneCheckoutAuthorizationHelper = require('*/cartridge/scripts/payone/payoneCheckoutAuthorizationHelper');

    var safeContext = context || {};
    var paymentInstruments = order.getPaymentInstruments();
    var paymentInstrument = paymentInstruments.length ? paymentInstruments[0] : null;

    return {
        mobilePaymentMethodSpecificInput: {
            paymentProductId: PAYMENT_PRODUCT_IDS.APPLE_PAY,
            authorizationMode: 'PRE_AUTHORIZATION',
            encryptedPaymentData: safeContext.paymentData.data,
            publicKeyHash: safeContext.paymentData.header.publicKeyHash,
            ephemeralKey: safeContext.paymentData.header.ephemeralPublicKey,
            threeDSecure: {
                redirectionData: {
                    returnUrl: payoneCheckoutAuthorizationHelper.buildReturnUrl(order, paymentInstrument)
                }
            },
            paymentProduct302SpecificInput: {
                integrationType: payoneCommerceApplePayHelper.getIntegrationType(),
                network: safeContext.paymentMethod.network.toUpperCase(),
                token: {
                    version: safeContext.paymentData.version.toUpperCase(),
                    signature: safeContext.paymentData.signature,
                    header: {
                        transactionId: safeContext.paymentData.header.transactionId
                    }
                },
                domainName: Site.getHttpsHostName(),
                displayName: Site.getName()
            }
        }
    };
}

module.exports = {
    PAYMENT_PRODUCT_IDS: PAYMENT_PRODUCT_IDS,
    buildBankAccountInformation: buildBankAccountInformation,
    buildBirthDateString: buildBirthDateString,
    buildCustomerOverride: buildCustomerOverride,
    buildPaymentMethodSpecificInput: buildPaymentMethodSpecificInput,
    getCardPaymentProductId: getCardPaymentProductId,
    getCardType: getCardType,
    getGooglePayEncryptedPaymentData: getGooglePayEncryptedPaymentData,
    getPayPalApprovalData: getPayPalApprovalData,
    getSecureInstallmentSelectionData: getSecureInstallmentSelectionData,
    getPostedField: getPostedField,
    getRequiredPostedField: getRequiredPostedField,
    getTokenInformation: getTokenInformation,
    getUnsupportedMethodMessage: getUnsupportedMethodMessage,
    normalizeTokenInformation: normalizeTokenInformation,
    requiresCustomerOverride: requiresCustomerOverride,
    supportsPaymentMethod: supportsPaymentMethod,
    buildApplePaySpecificInput: buildApplePaySpecificInput
};
